# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: ksops
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    binary: "{{ .ProjectName }}"

archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}

  - id: latest
    name_template: >-
      {{ .ProjectName }}_latest_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: viaduct-ai
    name: kustomize-sops

dockers:

  - use: buildx
  # Templates of the Docker image names.
    image_templates:
      - "viaductoss/{{ .ProjectName }}:latest-amd64"
      - "viaductoss/{{ .ProjectName }}:{{ .Tag }}-amd64"
      - "viaductoss/{{ .ProjectName }}:v{{ .Major }}-amd64"
      - "quay.io/viaductoss/{{ .ProjectName }}:latest-amd64"
      - "quay.io/viaductoss/{{ .ProjectName }}:{{ .Tag }}-amd64"
      - "quay.io/viaductoss/{{ .ProjectName }}:v{{ .Major }}-amd64"

    # Template of the docker build flags.
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/amd64"

    # If your Dockerfile copies files other than the binary itself,
    # you should list them here as well.
    # Note that goreleaser will create the same structure inside the temporary
    # folder, so if you add `foo/bar.json` here, on your Dockerfile you can
    # `COPY foo/bar.json /whatever.json`.
    # Also note that the paths here are relative to the folder in which
    # goreleaser is being run.
    # This field does not support wildcards, you can add an entire folder here
    # and use wildcards when you `COPY`/`ADD` in your Dockerfile.
    extra_files:
      - go.mod
      - go.sum
      - Makefile
      - scripts/
      - ksops.go
      # include .git for version
      - .git/

  - use: buildx
  # Templates of the Docker image names.
    image_templates:
      - "viaductoss/{{ .ProjectName }}:latest-arm64"
      - "viaductoss/{{ .ProjectName }}:{{ .Tag }}-arm64"
      - "viaductoss/{{ .ProjectName }}:v{{ .Major }}-arm64"
      - "quay.io/viaductoss/{{ .ProjectName }}:latest-arm64"
      - "quay.io/viaductoss/{{ .ProjectName }}:{{ .Tag }}-arm64"
      - "quay.io/viaductoss/{{ .ProjectName }}:v{{ .Major }}-arm64"

    # Template of the docker build flags.
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/arm64"


    # If your Dockerfile copies files other than the binary itself,
    # you should list them here as well.
    # Note that goreleaser will create the same structure inside the temporary
    # folder, so if you add `foo/bar.json` here, on your Dockerfile you can
    # `COPY foo/bar.json /whatever.json`.
    # Also note that the paths here are relative to the folder in which
    # goreleaser is being run.
    # This field does not support wildcards, you can add an entire folder here
    # and use wildcards when you `COPY`/`ADD` in your Dockerfile.
    extra_files:
      - go.mod
      - go.sum
      - Makefile
      - scripts/
      - ksops.go
      # include .git for version
      - .git/

docker_manifests:
- name_template: "viaductoss/{{ .ProjectName }}:latest"
  image_templates:
  - "viaductoss/{{ .ProjectName }}:latest-amd64"
  - "viaductoss/{{ .ProjectName }}:latest-arm64"

- name_template: "viaductoss/{{ .ProjectName }}:{{ .Tag }}"
  image_templates:
  - "viaductoss/{{ .ProjectName }}:{{ .Tag }}-amd64"
  - "viaductoss/{{ .ProjectName }}:{{ .Tag }}-arm64"


- name_template: "viaductoss/{{ .ProjectName }}:v{{ .Major }}"
  image_templates:
  - "viaductoss/{{ .ProjectName }}:v{{ .Major }}-amd64"
  - "viaductoss/{{ .ProjectName }}:v{{ .Major }}-arm64"

- name_template: "quay.io/viaductoss/{{ .ProjectName }}:latest"
  image_templates:
  - "quay.io/viaductoss/{{ .ProjectName }}:latest-amd64"
  - "quay.io/viaductoss/{{ .ProjectName }}:latest-arm64"

- name_template: "quay.io/viaductoss/{{ .ProjectName }}:{{ .Tag }}"
  image_templates:
  - "quay.io/viaductoss/{{ .ProjectName }}:{{ .Tag }}-amd64"
  - "quay.io/viaductoss/{{ .ProjectName }}:{{ .Tag }}-arm64"


- name_template: "quay.io/viaductoss/{{ .ProjectName }}:v{{ .Major }}"
  image_templates:
  - "quay.io/viaductoss/{{ .ProjectName }}:v{{ .Major }}-amd64"
  - "quay.io/viaductoss/{{ .ProjectName }}:v{{ .Major }}-arm64"
